### ISSUE TITLE
[긴급] 일부 영상에 대한 에러

### ISSUE THREAD

**Issue by junu-kk** [SoundPicker/SoundPicker-Server#10]
### 모든 영상이 다 잘 잘리는 게 아닌 것을 확인. 생성/수정 모두 똑같은 문제 발생
* szQUFX8NZ9E : 리버 영상인데 다운이 받아지지 않음. 우선 비슷한 영상으로 땜빵했으나 원인파악 필요.
* r3KwpvTakQo : 한국영화음악 모음 영상. 16분 정도까지만 다운받아짐.
* nPFe7I8ma2s : 외국영화음악 모음 영상. 11분 정도까지만 다운받아짐.

**Comment by junu-kk** [comment]
## [새로운 모듈](https://github.com/jeromeludmann/youtubemp3)을 찾았습니다

위 세 영상이 모두 잘 다운되는 것을 확인했고,  
무엇보다 기존 모듈보다  
획기적으로 속도가 개선된 것을 확인함.  

오늘중으로 도입할 예정!

**Comment by herimhong** [comment]
무슨 모듈인지 너무 기대되는중 두근두근

**Comment by junu-kk** [comment]
해결해서 push 완료!  
위 세 url 모두 잘 변환되는 것을 확인함.  
내일 create 말고 update도 새 모듈 반영 + ec2에서 잘 돌아가는지 확인할 예정
