### ISSUE TITLE
소켓 진행사항 공유

### ISSUE THREAD

**Issue by herimhong** [SoundPicker/SoundPicker-Server#9]
![socket_init](https://user-images.githubusercontent.com/66619693/104089764-d40aca80-52b4-11eb-8026-1f41cd57adb9.PNG)
- 보이는 그대로 답안을 쓰고 submit 버튼을 누르면 위에 테이블에 들어감

- 저런식으로 테이블을 만든다면 저 입력창 하나하나 선언을 해줘야돼서 플레이어가 늘수록 코드가 쓸데없이 길어질거같은데 저런식으로 테이블을 만드는게 맞는지에 대해 의문점을 품는중
- 입력한 답이 맞는지 확인하고 점수를 띄어주려면 DB랑 연동을 해야되는데 html&DB 연동 어떻게하는지 몰라서 헤매는중 🤔😱🤦🏻‍♀️

**Comment by junu-kk** [comment]
## 1차 소켓작업
### 💥💥app.js에 DB URL&PW가 그대로 노출되어있던 문제 발견💥💥
* 보안 관련해선 항상 주의합시당
* 강제푸시로 해당 커밋을 날렸어서, 풀받을때도 아마 강제풀 받아야할거야.
* 코드는 아래와 같습니다!
```
git pull -f origin feature/socket
```

<br/>

### 모듈화 - app.js
* app.js에선 api와 html을 단 순수 express앱을 리턴해주고
* www에선 익스프레스 앱을 포트 3000번과 연결해주며 소켓을 달아주고
* 이벤트가 들어왔을때 어떤 처리를 할지는 socket.js가 담당!

### 모듈화 - player.html
html도 이거저거 추가되면 길어질 것 같아서, css랑 js를 따로 분리했습니다~

<br/>

### 기타사항 & TODOs
* 포트 3000으로 통일하고, /realtime으로 들어갔을 떄 html 뜨게 함.
* DB연동 & 출제자뷰-테스터뷰 나눌 예정

**Comment by junu-kk** [comment]
**보이는 그대로 답안을 쓰고 submit 버튼을 누르면 위에 테이블에 들어감**
: 확인완료!

**저런식으로 테이블을 만든다면 저 입력창 하나하나 선언을 해줘야돼서 플레이어가 늘수록 코드가 쓸데없이 길어질거같은데 저런식으로 테이블을 만드는게 맞는지에 대해 의문점을 품는중**
* html에 테스트 인덱스를 입력할 수 있는 입력창을 만들고
* 입력해 submit하면 socket.js에 있는 로직이 실행될텐데, 거기서 DB연동을 처리하면 될듯!
* testCount값을 가져와서, js로 동적으로 row들을 만들면 될것같아.
* 요 부분은 비슷한 거 해본적이 있어서 함 도전해볼게

**입력한 답이 맞는지 확인하고 점수를 띄어주려면 DB랑 연동을 해야되는데 html&DB 연동 어떻게하는지 몰라서 헤매는중 🤔😱🤦🏻‍♀️**
: 윗 질문 답변으로 대체~!

**Comment by junu-kk** [comment]
새 리팩토링 프로젝트를 시작함에 따라 close 합니다.
(https://github.com/KangJunewoo/soundpicker-server)
